---
services: docker

env:
  - distro: fedora29
  - distro: ubuntu1804

script:
  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/nshenry03/3dca83668e6534f05678bd87eea64165/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh ${distro}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
