---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Setup NTP and Timezone
  import_role:
    name: geerlingguy.ntp

- name: Setup bash
  import_role:
    name: ansible-role-bash

- name: Setup Vim
  import_role:
    name: ansible-role-vim

- name: Ensure base packages are installed
  package:
    name: "{{ workstation_base_packages }}"
    state: present
