---
- name: Setup NTP and Timezone
  import_role:
    name: geerlingguy.ntp

- name: Setup bash
  import_role:
    name: ansible-role-bash

- name: Setup Vim
  import_role:
    name: ansible-role-vim
